const fs=require('fs'),path=require('path'),esbuild=require('esbuild');
const root=path.resolve(__dirname,'..');const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const projects=JSON.parse(read('source/projects.json')),credentials=JSON.parse(read('source/credentials.json'));
const bundle=esbuild.buildSync({entryPoints:[path.join(root,'source/scene.js')],bundle:true,minify:true,format:'iife',write:false}).outputFiles[0].text;
function escape(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
const cards=projects.map((p,i)=>`<article class="project-card" data-category="${escape(p.category)}"><div class="project-art tone-${i%4}" aria-hidden="true"><span class="art-number">FIELD NOTE / ${String(i+1).padStart(2,'0')}</span><div class="art-components">${p.nodes.map((n,j)=>`<div class="component"><span class="symbol">${['◇','▦','⎈'][j]}</span>${escape(n)}</div>`).join('<span class="component-arrow">→</span>')}</div><span class="art-stamp">ILLUSTRATIVE ARCHITECTURE</span></div><div class="project-body"><div class="project-meta"><span>${escape(p.label)}</span><span class="project-index">${String(i+1).padStart(2,'0')}</span></div><h3>${escape(p.title)}</h3><p>${escape(p.desc)}</p><div class="project-tags">${p.tags.map(t=>`<span>${escape(t)}</span>`).join('')}</div><div class="project-footer"><button class="case-button" data-case="${i}" aria-label="Read field notes for ${escape(p.title)}">Read field notes ↗</button><a href="https://github.com/lovish69/${p.repo}" target="_blank" rel="noopener noreferrer">Repository ↗</a></div></div></article>`).join('');
const publicURL='https://www.credly.com/users/lovish-barber.1481ab50/badges/credly';const badges=credentials.map(c=>`<article class="credential"><a href="${publicURL}" target="_blank" rel="noopener noreferrer" aria-label="View ${escape(c.title)} on public Credly profile"><img src="${c.image}" alt="${escape(c.title)} badge" width="100" height="100" loading="lazy"></a><span class="mono">${escape(c.issuer)}</span><h3>${escape(c.title)}</h3><p>${escape(c.date)}</p><a class="text-link" href="${publicURL}" target="_blank" rel="noopener noreferrer">View on Credly ↗</a></article>`).join('');
const replacements={FAVICON:'data:image/svg+xml,'+encodeURIComponent(read('favicon.svg')),FONTS:read('source/fonts.css'),CSS:read('source/style.css'),PROJECT_CARDS:cards,CREDENTIALS:badges,DATA:JSON.stringify(projects).replaceAll('<','\\u003c'),APP:read('source/app.js'),SCENE:bundle};
let html=read('source/template.html');for(const [key,value] of Object.entries(replacements))html=html.replace('__'+key+'__',()=>value);fs.writeFileSync(path.join(root,'index.html'),html);console.log('Built self-contained observatory:',Math.round(Buffer.byteLength(html)/1024),'KB');
