import * as THREE from 'three';
const canvas=document.querySelector('#observatory');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const stage=document.querySelector('.instrument');
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'low-power'})}catch(e){stage.classList.add('no-webgl');document.querySelector('#render-status').textContent='STATIC VIEW / EXPLORE PROJECTS BELOW';document.querySelectorAll('.webgl-control').forEach(x=>x.disabled=true);}
if(renderer){
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(7.5,5.4,9.5);camera.lookAt(0,.15,0);
scene.add(new THREE.AmbientLight(0xdde8ff,1.7));let light=new THREE.DirectionalLight(0xffffff,3);light.position.set(4,7,6);scene.add(light);light=new THREE.DirectionalLight(0x7b9eff,1.7);light.position.set(-5,1,-2);scene.add(light);light=new THREE.DirectionalLight(0xffb568,1.1);light.position.set(2,-3,4);scene.add(light);
const starsGeometry=new THREE.BufferGeometry();const starPositions=[];for(let i=0;i<110;i++){const a=i*2.39996,r=4.1+(i%9)*.22;starPositions.push(Math.cos(a)*r,Math.sin(i*8.2)*3.3,Math.sin(a)*r)}starsGeometry.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));const stars=new THREE.Points(starsGeometry,new THREE.PointsMaterial({color:0x739fde,size:.023,transparent:true,opacity:.6,depthWrite:false}));scene.add(stars);
const world=new THREE.Group();world.rotation.z=.05;scene.add(world);const assembly=new THREE.Group();world.add(assembly);
const blue=new THREE.MeshStandardMaterial({color:0x275bd9,metalness:.65,roughness:.3});const midnight=new THREE.MeshStandardMaterial({color:0x102b64,metalness:.55,roughness:.3});const cream=new THREE.MeshStandardMaterial({color:0x9fc4ed,metalness:.45,roughness:.25});const orange=new THREE.MeshStandardMaterial({color:0xff713e,metalness:.18,roughness:.25});const chrome=new THREE.MeshStandardMaterial({color:0xcbd7df,metalness:.92,roughness:.18});const allMats=[blue,midnight,cream,orange,chrome];
const slabs=[],satellites=[],pickables=[];const axis=new THREE.Vector3(0,1,0);
function box(w,h,d,mat,x,y,z,parent=assembly){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.position.set(x,y,z);parent.add(o);return o}
function cyl(r1,r2,h,mat,x,y,z,parent=assembly,segments=64){const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,segments),mat);o.position.set(x,y,z);parent.add(o);return o}
function ring(r,t,mat,parent=assembly){const o=new THREE.Mesh(new THREE.TorusGeometry(r,t,10,100),mat);parent.add(o);return o}
// Seven mechanically layered decks around a common spine.
const levels=[[-1.15,1.46,.22,blue],[-.84,1.28,.13,cream],[-.5,1.34,.22,midnight],[-.12,1.17,.12,orange],[.2,1.34,.22,blue],[.55,1.22,.13,cream],[.88,1.4,.22,blue]];
levels.forEach(([y,r,h,material],i)=>{const g=new THREE.Group();g.position.y=y;assembly.add(g);cyl(r,r,h,material,0,0,0,g,8).rotation.y=Math.PI/8;const track=ring(r*.82,.018,chrome,g);track.rotation.x=Math.PI/2;track.position.y=h/2+.01;for(let k=0;k<8;k++){let a=k/8*Math.PI*2+Math.PI/8;cyl(.045,.045,.03,orange,Math.cos(a)*r*.86,h/2+.025,Math.sin(a)*r*.86,g,10)}if(i===2||i===4){for(let k=0;k<12;k++){const a=k/12*Math.PI*2;const tab=box(.13,.075,.1,cream,Math.cos(a)*1.27,0,Math.sin(a)*1.27,g);tab.rotation.y=-a}}slabs.push({g,y})});
cyl(.22,.22,2.4,chrome,0,-.12,0);cyl(.37,.37,.16,orange,0,1.06,0);
const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.55,1),cream);core.position.y=1.55;assembly.add(core);const outline=new THREE.LineSegments(new THREE.EdgesGeometry(core.geometry),new THREE.LineBasicMaterial({color:0x2f59c2,transparent:true,opacity:.6}));core.add(outline);
const arc1=ring(2.25,.047,blue);arc1.rotation.x=.75;arc1.rotation.y=.3;
const arc2=ring(2.37,.021,orange);arc2.rotation.x=-.7;arc2.rotation.y=.85;
const arc3=ring(2.53,.012,chrome);arc3.rotation.x=1.45;
const path=new THREE.EllipseCurve(0,0,2.26,2.26,0,Math.PI*.4,false,0);const tube=new THREE.TubeGeometry(new THREE.CatmullRomCurve3(path.getPoints(40).map(p=>new THREE.Vector3(p.x,p.y,0))),40,.09,8,false);const accent=new THREE.Mesh(tube,orange);arc1.add(accent);
function label(text){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#101f38';ctx.beginPath();ctx.roundRect(3,18,506,92,10);ctx.fill();ctx.strokeStyle='#527dbb';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#c6dbff';ctx.font='500 43px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,65);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false,transparent:true,toneMapped:false}));sp.scale.set(1.42,.355,1);return sp}
const names=['AWS / EKS','TERRAFORM','GITOPS','OBSERVE'];const types=[0,1,5,2];
for(let i=0;i<4;i++){const a=i*Math.PI/2+.3;const g=new THREE.Group();world.add(g);g.position.set(Math.cos(a)*2.75,Math.sin(a*2)*.65,Math.sin(a)*2.75);const base=cyl(.42,.45,.19,blue,0,0,0,g,6);cyl(.3,.3,.22,cream,0,.2,0,g,6);const node=cyl(.19,.19,.15,orange,0,.4,0,g,6);[base,node].forEach(o=>{o.userData.index=types[i];pickables.push(o)});const sp=label(names[i]);sp.position.y=.87;sp.userData.index=types[i];g.add(sp);pickables.push(sp);satellites.push({g,a})}
const lineMat=new THREE.LineDashedMaterial({color:0x6984bd,dashSize:.08,gapSize:.08,transparent:true,opacity:.4});const connectors=[];satellites.forEach(s=>{const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),s.g.position]);const l=new THREE.Line(geometry,lineMat);l.computeLineDistances();world.add(l);connectors.push(l)});
// A ground reference ring gives the floating instrument its spatial context.
const ground=new THREE.Group();ground.position.y=-2.4;world.add(ground);const circle=ring(2.7,.012,chrome,ground);circle.rotation.x=Math.PI/2;for(let i=0;i<48;i++){const a=i/48*Math.PI*2;const tick=box(.018,.008,i%4===0?.16:.07,blue,Math.sin(a)*2.7,0,Math.cos(a)*2.7,ground);tick.rotation.y=a}
let paused=reduced.matches,drag=false,moved=false,lastX=0,lastY=0,visible=true,target=0,spread=0,t=0,last=0;
const explode=document.querySelector('#explode');explode.addEventListener('input',()=>{target=Number(explode.value)/100;document.querySelector('#spread-value').textContent=Math.round(target*100)+'%';document.querySelector('#mode-label').textContent=target>.5?'EXPLODED ASSEMBLY':'ASSEMBLED SYSTEM'});
const pause=document.querySelector('#pause-scene');function update(){pause.setAttribute('aria-pressed',String(paused));pause.innerHTML=paused?'Play rotation <span>▷</span>':'Pause rotation <span>Ⅱ</span>'}pause.addEventListener('click',()=>{paused=!paused;update()});reduced.addEventListener('change',()=>{paused=reduced.matches;update()});update();
const wire=document.querySelector('#wireframe');wire.addEventListener('click',()=>{const on=wire.getAttribute('aria-pressed')!=='true';wire.setAttribute('aria-pressed',String(on));allMats.forEach(m=>m.wireframe=on);document.querySelector('#render-status').textContent=on?'WIREFRAME / GEOMETRY VIEW':'WEBGL / REAL-TIME RENDER'});
document.querySelector('#reset-scene').addEventListener('click',()=>{world.rotation.set(0,0,.05);explode.value=0;target=0;document.querySelector('#spread-value').textContent='0%';document.querySelector('#mode-label').textContent='ASSEMBLED SYSTEM';allMats.forEach(m=>m.wireframe=false);wire.setAttribute('aria-pressed','false');document.querySelector('#render-status').textContent='WEBGL / REAL-TIME RENDER'});
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();function hit(e){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return ray.intersectObjects(pickables)[0]}
canvas.addEventListener('pointerdown',e=>{drag=true;moved=false;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;world.rotation.y+=dx*.006;world.rotation.x=THREE.MathUtils.clamp(world.rotation.x+dy*.003,-.35,.35);lastX=e.clientX;lastY=e.clientY}else{canvas.style.cursor=hit(e)?'pointer':'grab'}});canvas.addEventListener('pointerup',e=>{drag=false;if(!moved){const obj=hit(e);if(obj)window.openProject?.(obj.object.userData.index)}});canvas.addEventListener('pointercancel',()=>drag=false);
canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')world.rotation.y-=.12;if(e.key==='ArrowRight')world.rotation.y+=.12;if(e.key==='ArrowUp')world.rotation.x=Math.max(-.35,world.rotation.x-.06);if(e.key==='ArrowDown')world.rotation.x=Math.min(.35,world.rotation.x+.06)}});
new ResizeObserver(()=>{const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(7.5,5.4,9.5).multiplyScalar(w<450?1.3:1);camera.lookAt(0,.15,0);camera.updateProjectionMatrix()}).observe(canvas);
new IntersectionObserver(es=>visible=es[0].isIntersecting).observe(stage);
function render(time){requestAnimationFrame(render);const dt=Math.min(time-last||16,45);last=time;if(!visible||document.hidden)return;spread=reduced.matches?target:THREE.MathUtils.lerp(spread,target,.06);if(!paused){t+=dt;if(!drag)world.rotation.y+=dt*.00009;core.rotation.y+=dt*.0005;}slabs.forEach(o=>o.g.position.y=o.y*(1+spread*.75));core.position.y=1.55+spread*.9;arc1.rotation.z=t*.0001;arc2.rotation.z=-t*.00008;ground.position.y=-2.4-spread*.2;satellites.forEach((s,i)=>{const r=2.75+spread*.6;s.g.position.set(Math.cos(s.a)*r,Math.sin(s.a*2)*.65+(paused?0:Math.sin(t*.001+i)*.08),Math.sin(s.a)*r);connectors[i].geometry.setFromPoints([new THREE.Vector3(),s.g.position]);connectors[i].computeLineDistances()});renderer.render(scene,camera)}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();stage.classList.add('no-webgl');document.querySelector('#render-status').textContent='3D UNAVAILABLE / USE PROJECT LINKS'});requestAnimationFrame(render);
}

// Independent, on-demand renderer for the interactive delivery-platform bench.
(()=>{
const canvas=document.getElementById('platform-canvas'),stage=canvas.parentElement;
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'low-power'})}catch(e){stage.classList.add('lab-no-webgl');stage.querySelectorAll('.lab-view-control').forEach(b=>b.disabled=true);return}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(9.5,9,11);camera.lookAt(0,.25,0);
scene.add(new THREE.AmbientLight(0xc4d9ff,1.8));const key=new THREE.DirectionalLight(0xc4deff,4);key.position.set(3,8,5);scene.add(key);const rim=new THREE.PointLight(0x3769ff,65,25);rim.position.set(-5,4,-2);scene.add(rim);const warm=new THREE.PointLight(0xff8655,40,20);warm.position.set(5,4,3);scene.add(warm);
const world=new THREE.Group();scene.add(world);const materials={dark:new THREE.MeshStandardMaterial({color:0x152846,metalness:.6,roughness:.34}),blue:new THREE.MeshStandardMaterial({color:0x346bf0,metalness:.5,roughness:.27}),silver:new THREE.MeshStandardMaterial({color:0x94b6d8,metalness:.65,roughness:.28}),orange:new THREE.MeshStandardMaterial({color:0xfd8b55,metalness:.25,roughness:.3}),black:new THREE.MeshStandardMaterial({color:0x091427,metalness:.45,roughness:.4})};
const emitBlue=new THREE.MeshBasicMaterial({color:0x84baff}),emitOrange=new THREE.MeshBasicMaterial({color:0xffa578});
function box(w,h,d,m,x,y,z,parent=world){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);parent.add(mesh);return mesh}
function cylinder(r,h,m,x,y,z,parent=world,segments=32){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments),m);mesh.position.set(x,y,z);parent.add(mesh);return mesh}
function edge(m,color=0x6a92ce){const line=new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color,transparent:true,opacity:.5}));m.add(line)}
const board=box(8.7,.22,6.2,materials.black,0,-.75,0);edge(board);const inset=box(8.4,.055,5.9,materials.dark,0,-.61,0);edge(inset,0x3c689f);const grid=new THREE.GridHelper(8.3,24,0x4a70ac,0x233c61);grid.scale.z=.69;grid.position.y=-.57;world.add(grid);
const pos=[[-2.1,-1.5],[2.1,-1.5],[2.1,1.5],[-2.1,1.5]],names=['01 / PROVISION','02 / BUILD','03 / DEPLOY','04 / OBSERVE'],groups=[],highlights=[],pickables=[];
function label(text){const c=document.createElement('canvas');c.width=640;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#0a172c';ctx.beginPath();ctx.roundRect(4,20,632,88,10);ctx.fill();ctx.strokeStyle='#688ed0';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#d0e3ff';ctx.font='500 35px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,320,65);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false,toneMapped:false}));sp.scale.set(1.75,.35,1);return sp}
for(let i=0;i<4;i++){const g=new THREE.Group();g.position.set(pos[i][0],-.37,pos[i][1]);world.add(g);groups.push(g);const pad=box(2.75,.18,2.13,materials.dark,0,0,0,g);edge(pad);const highlight=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(2.79,.23,2.17)),new THREE.LineBasicMaterial({color:i===0?0xffa578:0x436cba,transparent:true,opacity:i===0?1:.45}));g.add(highlight);highlights.push(highlight);pad.userData.station=i;pickables.push(pad);const plate=label(names[i]);plate.position.set(0,1.65,0);plate.userData.station=i;g.add(plate);pickables.push(plate)}
// 01: three rack units with individual ventilation slots and status lights.
const infra=groups[0];for(let j=0;j<3;j++){const m=box(1.1,.3,.92,j===1?materials.blue:materials.dark,0,.3+j*.36,0,infra);edge(m);for(let k=0;k<4;k++)box(.5,.022,.035,materials.silver,-.16,.22+j*.36+k*.045,.48,infra);box(.08,.055,.04,emitBlue,.34,.3+j*.36,.48,infra)}
// 02: stacked container packages under a security inspection arch.
const build=groups[1];[[-.48,.32,.22],[.35,.32,.22],[-.05,.85,-.12]].forEach(([x,y,z],i)=>{const m=box(.69,.48,.68,i===2?materials.orange:materials.blue,x,y,z,build);edge(m);for(let j=0;j<4;j++)box(.025,.33,.024,materials.silver,x-.22+j*.14,y,z+.352,build)});box(.08,1.27,.08,materials.silver,-1,.69,-.4,build);box(.08,1.27,.08,materials.silver,1,.69,-.4,build);box(2.08,.08,.08,emitOrange,0,1.29,-.4,build);
// 03: pod cluster arranged around a hexagonal scheduling core.
const cluster=groups[2];const core=cylinder(.35,.32,materials.blue,0,.35,0,cluster,6);edge(core);for(let i=0;i<6;i++){const a=i/6*Math.PI*2;const x=Math.cos(a)*.74,z=Math.sin(a)*.7;const pod=cylinder(.16,.44,i%2?materials.silver:materials.blue,x,.45,z,cluster,6);edge(pod);cylinder(.08,.035,emitBlue,x,.69,z,cluster,12);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,.22,0),new THREE.Vector3(x,.22,z)]),new THREE.LineBasicMaterial({color:0x769ce0}));cluster.add(line)}
// 04: actual chart texture on a three-dimensional monitoring panel.
const observe=groups[3];box(.23,.42,.22,materials.silver,0,.3,0,observe);box(1.08,.08,.52,materials.dark,0,.11,.1,observe);const screen=box(1.7,.96,.12,materials.dark,0,.95,0,observe);edge(screen);const monitorCanvas=document.createElement('canvas');monitorCanvas.width=640;monitorCanvas.height=360;const c=monitorCanvas.getContext('2d');c.fillStyle='#09162c';c.fillRect(0,0,640,360);c.fillStyle='#8facd8';c.font='20px monospace';c.fillText('RESOURCE SIGNALS / DEMO',25,36);c.strokeStyle='#203658';c.lineWidth=2;for(let y=75;y<350;y+=50){c.beginPath();c.moveTo(25,y);c.lineTo(610,y);c.stroke()}for(let k=0;k<2;k++){c.beginPath();for(let i=0;i<=30;i++){const x=25+i*19,y=170+k*85+Math.sin(i*.55+k)*28-Math.sin(i*.12)*25;if(!i)c.moveTo(x,y);else c.lineTo(x,y)}c.strokeStyle=k?'#ffae78':'#77b2ff';c.lineWidth=5;c.stroke()}const texture=new THREE.CanvasTexture(monitorCanvas);texture.colorSpace=THREE.SRGBColorSpace;const face=new THREE.Mesh(new THREE.PlaneGeometry(1.53,.81),new THREE.MeshBasicMaterial({map:texture,toneMapped:false}));face.position.set(0,.95,.066);observe.add(face);
// Every piece of each model is a selectable part of its station.
groups.forEach((g,index)=>g.traverse(o=>{if(o.isMesh&&!pickables.includes(o)){o.userData.station=index;pickables.push(o)}}));
const routes=[],packets=[];for(let i=0;i<4;i++){const a=new THREE.Vector3(pos[i][0],-.49,pos[i][1]),b=new THREE.Vector3(pos[(i+1)%4][0],-.49,pos[(i+1)%4][1]);const curve=new THREE.CatmullRomCurve3([a,new THREE.Vector3(a.x*.55,-.49,a.z*.55),new THREE.Vector3(b.x*.55,-.49,b.z*.55),b]);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(35)),new THREE.LineBasicMaterial({color:0x608fd9,transparent:true,opacity:.7}));world.add(line);routes.push(curve);const packet=new THREE.Mesh(new THREE.SphereGeometry(.063,8,8),emitOrange);world.add(packet);packets.push(packet)}
let index=0;window.addEventListener('platform-stage',e=>{if(!Number.isInteger(e.detail)||e.detail<0||e.detail>3)return;index=e.detail;highlights.forEach((h,i)=>{h.material.color.setHex(i===index?0xffa578:0x436cba);h.material.opacity=i===index?1:.45})});
let mode='iso',visible=true,paused=reduced.matches,drag=false,moved=false,lastX=0,lastY=0,time=0,last=0;const targetCamera=new THREE.Vector3();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.view;world.rotation.set(0,0,0);document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))})}));const pause=document.getElementById('pause-platform');function updatePause(){pause.setAttribute('aria-pressed',String(paused));pause.textContent=paused?'Play flow ▷':'Pause flow Ⅱ'}pause.addEventListener('click',()=>{paused=!paused;updatePause()});reduced.addEventListener('change',()=>{paused=reduced.matches;updatePause()});updatePause();
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();function hit(e){const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return ray.intersectObjects(pickables)[0]}
canvas.addEventListener('pointerdown',e=>{drag=true;moved=false;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;world.rotation.y+=dx*.005;world.rotation.x=THREE.MathUtils.clamp(world.rotation.x+dy*.002,-.17,.22);lastX=e.clientX;lastY=e.clientY}else{canvas.style.cursor=hit(e)?'pointer':'grab'}});canvas.addEventListener('pointerup',e=>{drag=false;if(!moved){const h=hit(e);if(h)window.selectWorkflow?.(h.object.userData.station)}});canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')world.rotation.y-=.13;if(e.key==='ArrowRight')world.rotation.y+=.13;if(e.key==='ArrowUp')world.rotation.x=Math.max(-.17,world.rotation.x-.05);if(e.key==='ArrowDown')world.rotation.x=Math.min(.22,world.rotation.x+.05)}});
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas);new IntersectionObserver(es=>visible=es[0].isIntersecting).observe(stage);resize();
function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-last)||16,40);last=t;if(!visible||document.hidden)return;const narrow=canvas.clientWidth<480?1.4:1;targetCamera.copy(mode==='top'?new THREE.Vector3(.05,16,.05):new THREE.Vector3(9.5,9,11)).multiplyScalar(narrow);camera.position.lerp(targetCamera,reduced.matches?1:.07);camera.lookAt(0,.25,0);if(!paused)time+=dt;groups.forEach((g,i)=>{const y=i===index?-.18:-.37;g.position.y=THREE.MathUtils.lerp(g.position.y,y,reduced.matches?1:.08)});packets.forEach((p,i)=>p.position.copy(routes[i].getPoint((time*.00015+i*.22)%1)));renderer.render(scene,camera)}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();stage.classList.add('lab-no-webgl');stage.querySelectorAll('.lab-view-control').forEach(b=>b.disabled=true)});requestAnimationFrame(animate);
})();
